#!/usr/bin/env python3
"""
aider_loop.py

Backward-compatibility facade for forge.

Previously, all loop logic lived in this file. The functionality has been
deconstructed into modular components:
- forge.config: Configuration file loading and settings lookups
- forge.todo: Checklist parsing, status tracking, and item serialization
- forge.validator: Preflight checks, syntax checking, and scope enforcement
- forge.tdd: Test-driven development (red/green) workflow
- forge.runner: Execution orchestrator, review gate, and worker management

All symbols are re-exported here so existing callers, subcommands, scripts,
and tests continue to work without modification.
"""

from .config import (
    CONFIG,
    CONFIG_FILENAME,
    DEFAULT_MAX_FILE_BYTES,
    DEFAULT_MAX_ITEMS,
    DEFAULT_MAX_RETRIES,
    DEFAULT_MAX_VALIDATION_RETRIES,
    DEFAULT_SLEEP_BETWEEN_ITEMS,
    EXCLUDE_DIRS,
    _log_lock,
    cfg,
    check_ollama_context,
    load_config,
    log,
    resolve_models,
)
from .runner import (
    _AIDER_TOKENS_RE,
    DIFFICULTY_EASY,
    DIFFICULTY_HARD,
    _accumulate_usage,
    _fallback_label,
    _should_fall_back,
    estimate_difficulty,
    git_head,
    is_git_repo,
    log_run_summary,
    main,
    parse_aider_token_line,
    process_item,
    record_run,
    run_aider_on_item,
    run_editor_on_item,
    run_parallel,
    run_review_gate,
)
from .tdd import (
    TDD_PREFIX_RE,
    classify_tdd_files,
    is_tdd_item,
    run_tdd_phases,
)
from .todo import (
    CHECKBOX_RE,
    STATUS_BLOCKED,
    STATUS_DONE,
    STATUS_NEEDS_REVIEW,
    STATUS_OPEN,
    TodoItem,
    _CHECKPOINT_RE,
    next_open_item,
    parse_todo,
    parse_todo_lines,
    preflight_todo_rules,
    update_item_status,
    write_todo,
)
from .validator import (
    FILE_PATH_RE,
    NEGATION_NEAR_RE,
    PROMPT_LEAKAGE_MARKERS,
    _COMMON_EXTENSIONS,
    _FENCE_RE,
    _JINJA_COMMENT_RE,
    _JINJA_EXPR_RE,
    _JINJA_STMT_RE,
    _WINDOWS_ILLEGAL_CHARS_RE,
    _looks_like_code_reference,
    _negates,
    _negates_before,
    _normalize_content,
    changed_files,
    check_syntax_only,
    content_mismatches,
    detect_prompt_leakage,
    expected_files,
    extract_exact_content_specs,
    find_js_html_files,
    find_python_files,
    package_json_or_js_html_present,
    path_matches_any,
    preflight_repo_size,
    restore_unnamed_files,
    run_configured_commands,
    strip_template_syntax,
    suspicious_new_paths,
    validate_js_html,
    validate_python,
    validate_syntax,
)

__all__ = [
    "CONFIG",
    "CONFIG_FILENAME",
    "DEFAULT_MAX_FILE_BYTES",
    "DEFAULT_MAX_ITEMS",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_MAX_VALIDATION_RETRIES",
    "DEFAULT_SLEEP_BETWEEN_ITEMS",
    "EXCLUDE_DIRS",
    "_log_lock",
    "cfg",
    "check_ollama_context",
    "load_config",
    "log",
    "resolve_models",
    "STATUS_OPEN",
    "STATUS_DONE",
    "STATUS_BLOCKED",
    "STATUS_NEEDS_REVIEW",
    "CHECKBOX_RE",
    "_CHECKPOINT_RE",
    "TodoItem",
    "parse_todo",
    "parse_todo_lines",
    "write_todo",
    "next_open_item",
    "update_item_status",
    "preflight_todo_rules",
    "FILE_PATH_RE",
    "_COMMON_EXTENSIONS",
    "_looks_like_code_reference",
    "find_js_html_files",
    "find_python_files",
    "run_configured_commands",
    "validate_python",
    "_JINJA_EXPR_RE",
    "_JINJA_STMT_RE",
    "_JINJA_COMMENT_RE",
    "strip_template_syntax",
    "validate_js_html",
    "check_syntax_only",
    "validate_syntax",
    "package_json_or_js_html_present",
    "preflight_repo_size",
    "NEGATION_NEAR_RE",
    "path_matches_any",
    "_FENCE_RE",
    "_negates_before",
    "_negates",
    "expected_files",
    "PROMPT_LEAKAGE_MARKERS",
    "detect_prompt_leakage",
    "_WINDOWS_ILLEGAL_CHARS_RE",
    "suspicious_new_paths",
    "extract_exact_content_specs",
    "_normalize_content",
    "content_mismatches",
    "changed_files",
    "restore_unnamed_files",
    "TDD_PREFIX_RE",
    "is_tdd_item",
    "classify_tdd_files",
    "run_tdd_phases",
    "DIFFICULTY_EASY",
    "DIFFICULTY_HARD",
    "estimate_difficulty",
    "is_git_repo",
    "git_head",
    "run_aider_on_item",
    "_AIDER_TOKENS_RE",
    "parse_aider_token_line",
    "_fallback_label",
    "_should_fall_back",
    "run_editor_on_item",
    "_accumulate_usage",
    "record_run",
    "log_run_summary",
    "run_review_gate",
    "process_item",
    "run_parallel",
    "main",
]

if __name__ == "__main__":
    raise SystemExit(main())
